input:
  type: rabbitmq
  host: localhost
  port: 5672
  queue: planted-trees.raw

parser:
  parse_to: json
  delimiter: "|"

fields:
  - name: message
    type: str

  - name: arad_age
    type: int

  - name: event_time
    type: datetime
    format: "%Y-%m-%dT%H:%M:%S.%fNZ"

  - name: reporter_name
    type: str

  - name: address
    type: str

  - name: phone.phone_number
    type: str

  - name: phone.phone_type
    type: str

output:
  type: rabbitmq
  host: localhost
  port: 5672
  exchange: planted-trees.events
  routing_key: parsed

logging:
  level: DEBUG
